### PR TITLE
Add list of fonts excluded from having previews generated.  

### LINKED ISSUE #18: Some SVG image previews are clipped or not rendered legibly in GB 17.6
This is an updated list (see https://github.com/WordPress/gutenberg/issues/54688) of default font collection SVGs that are not rendered correctly or are clipped, as of Gutenberg 17.6.

```
chenla
coiny
concert-one
content
cutive
englebert
khmer
liu-jian-mao-cao
material-icons
material-icons-outlined
material-icons-round
material-icons-sharp
material-icons-two-tone
noto-color-emoji
noto-emoji
noto-emoji
noto-kufi-arabic
noto-sans-arabic
noto-sans-lycian
noto-sans-myanmar
noto-sans-phags-pa
noto-sans-signwriting
noto-serif-myanmar
revalia
siemreap
updock
```

<details closed>
<summary>Expand for a list of source SVGs...</summary>

```
https://s.w.org/images/fonts/17.6/previews/chenla/chenla.svg
https://s.w.org/images/fonts/17.6/previews/coiny/coiny.svg
https://s.w.org/images/fonts/17.6/previews/concert-one/concert-one.svg
https://s.w.org/images/fonts/17.6/previews/content/content.svg
https://s.w.org/images/fonts/17.6/previews/cutive/cutive.svg
https://s.w.org/images/fonts/17.6/previews/englebert/englebert.svg
https://s.w.org/images/fonts/17.6/previews/khmer/khmer.svg
https://s.w.org/images/fonts/17.6/previews/liu-jian-mao-cao/liu-jian-mao-cao.svg
https://s.w.org/images/fonts/17.6/previews/material-icons/material-icons.svg
https://s.w.org/images/fonts/17.6/previews/material-icons-outlined/material-icons-outlined.svg
https://s.w.org/images/fonts/17.6/previews/material-icons-round/material-icons-round.svg
https://s.w.org/images/fonts/17.6/previews/material-icons-sharp/material-icons-sharp.svg
https://s.w.org/images/fonts/17.6/previews/material-icons-two-tone/material-icons-two-tone.svg
https://s.w.org/images/fonts/17.6/previews/noto-color-emoji/noto-color-emoji.svg
https://s.w.org/images/fonts/17.6/previews/noto-emoji/noto-emoji.svg
https://s.w.org/images/fonts/17.6/previews/noto-emoji/noto-emoji.svg
https://s.w.org/images/fonts/17.6/previews/noto-kufi-arabic/noto-kufi-arabic.svg
https://s.w.org/images/fonts/17.6/previews/noto-sans-arabic/noto-sans-arabic.svg
https://s.w.org/images/fonts/17.6/previews/noto-sans-lycian/noto-sans-lycian.svg
https://s.w.org/images/fonts/17.6/previews/noto-sans-myanmar/noto-sans-myanmar.svg
https://s.w.org/images/fonts/17.6/previews/noto-sans-phags-pa/noto-sans-phags-pa.svg
https://s.w.org/images/fonts/17.6/previews/noto-sans-signwriting/noto-sans-signwriting.svg
https://s.w.org/images/fonts/17.6/previews/noto-serif-myanmar/noto-serif-myanmar.svg
https://s.w.org/images/fonts/17.6/previews/revalia/revalia.svg
https://s.w.org/images/fonts/17.6/previews/siemreap/siemreap.svg
https://s.w.org/images/fonts/17.6/previews/updock/updock.svg
```

</details>

### PR DESCRIPTION
**Pull request by pbking**
Also added ability to render a single font family preview via command line.

`node src/generate_font_previews.js font-family-slug`

Also added a collection of font faces that have poorly generated previews.  (See #18)

Those fonts will render in the UI instead of depending on the previews.

Better would be to determine why the previews aren't being generated correctly.  Until/unless that happens this might be an acceptable band-aid.

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
I haven't try this PR yet, but I'm curious how those fonts render without a preview image. 
Does not adding a preview solve the problem?

**Comment by pbking** [comment]
> I'm curious how those fonts render without a preview image.
Does not adding a preview solve the problem?

Yes, the (few) fonts that don't have a preview URL load the fonts for the Font Library UI.  

Before:
image

After:
image

It's unclear to me why these fonts don't generate a preview as expected, yet render fine in a browser.  However this does allow them to render as expected.

**Comment by ironprogrammer** [comment]
Thank you for digging into this, @pbking!

For problematic fonts without glyphs to support printing existing previews, could the exclusion list include an [optional?] alternate string of existing glyphs to use instead?

E.g. for [Chenla](https://fonts.google.com/specimen/Chenla?query=chenla), something like `ឈិនឡា` (Google Translate says that's "Chenla" in Khmer). Perhaps online search and the polyglots community can help identify good strings to use for this relatively short list.

And if there are remaining fonts with missing default glyphs that don't spell anything, then this string could be used to exhibit a sample of glyphs a user would have access to.

**Comment by mikachan** [comment]
> For problematic fonts without glyphs to support printing existing previews, could the exclusion list include an [optional?] alternate string of existing glyphs to use instead?

I think this is a great idea, although I think it would be best to implement this in a follow-up. That means we could land this PR sooner to fix the broken font previews for 6.5.

@pbking @matiasbenedetto What do you think?

**Comment by pbking** [comment]
I believe it might be a valid follow up.  It might be relevant to just provide custom SVGs for certain font families/faces too rather than generate those.  The list is likely small and the work involved maybe not worthwhile for such a few exceptions.

This change fixes the issue at hand.  I rather thing it should come in as a fix for now.  If we want to get fancier then let's document and fix that sometime down the road.

**Review by mikachan — APPROVED** [review]
> This change fixes the issue at hand. I rather thing it should come in as a fix for now. If we want to get fancier then let's document and fix that sometime down the road.

Makes sense, let's bring this in 👍

**Pull request merged**
