### PR TITLE
Add core 6.5 release

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Add a font collection data file that accommodates the changes being made in https://github.com/WordPress/wordpress-develop/pull/6130 regarding the signature of the `wp_register_font_collection` function.

## Why?
The signature of the `wp_register_font_collection` function changes, and the font collection should include only the list of font families. The ones removed in this PR (`name,` `description`, and `categories`) will be required to be included in PHP to make them translatable.

## Note
The previews haven't been regenerated, so the preview links still point to the 17.7 version. There's no need to change them to test the shape of the font collection JSON file.

## Testing instructions.
1. Use latest WordPress RC version available.
2. Replace the registered [google fonts collection data URL](https://github.com/WordPress/wordpress-develop/blob/7e1b5bac092ab28b0738d0a5bd7eda723acd8e79/src/wp-includes/fonts.php#L197) and use this one: `https://raw.githubusercontent.com/WordPress/google-fonts-to-wordpress-collection/efc23ab867b7515e738dfe8d682fb57f9b3fcfe6/releases/wp-6.5/collections/google-fonts-with-preview.json`
3. Check that the google fonts collection is working as expected.

### CODE REVIEW

**Comment by creativecoder** [comment]
@matiasbenedetto How should we proceed with this font collection change? Is it time to create a release folder for WP 6.5?

**Comment by matiasbenedetto** [comment]
> Is it time to create a release folder for WP 6.5?

Yes, I renamed the folder from `core-6.5.beta` to `core-6.5`.

> How should we proceed with this font collection change?

 There's no need to duplicate the preview files because they were not re-generated.
 I'll bring the changes from https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/20 and update the PR.

**Comment by matiasbenedetto** [comment]
I integrated the changes from https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/20 in https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/21/commits/ef371a27f7a8e100144f52ca137e3b42c4d18e57

The PR seems ready to go now.
Please test it to confirm.

**Review by creativecoder — APPROVED** [review]
✅ Verified that font json files are the same between gutenberg-17.7 and core-6.5, except for the removed properties.

I think `wp-6.5` would be clearer as a directory name. "core" seems like it's usually usually used more abstractly, some people say Gutenberg is "part of core." While wp-6.5 is clearly a release version of WordPress.

**Pull request merged**
