### PR TITLE
Add Google Fonts capability option

### LINKED ISSUE #1: Downloads TTF files instead of WOFF/WOFF2
This was brought up in the Gutenberg repo (see https://github.com/WordPress/gutenberg/issues/55049 and https://github.com/WordPress/gutenberg/pull/57706), as well as WP's Slack.
Currently we're downloading `.ttf` files which are quite large and don't support all features that modern font-families have.
We should instead download `.woff` files, or - ideally - `.woff2`.
We should be able to do that by passing a user-agent in the `fetch` call on https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/abe0da82028cbd99bfcf8577cd8a88e8c863f7d4/src/get_google_fonts.js#L80

User-agents we can use:
If we want to get `woff` files, then the one below is the recommended user-agent since it's the only one that also supports unicode-ranges
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
```

If we want to get `woff2` files, then this one will do:
```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
```

cc @matiasbenedetto

### PR DESCRIPTION
**Pull request by mikachan**
This adds the Google Fonts [capability option](https://developers.google.com/fonts/docs/developer_api#optimization) and sets it to `WOFF2`. This means the font assets that are downloaded will be `WOFF2` instead of `TTF`.

This may be easier to review by looking at each commit, as the update to all the font files is making GH very slow 😅

- Most relevant change, adding the capability param: https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/3/commits/29b2efa1228308af8382c8bab3529bafc9c36437
- Some code quality tweaks: https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/3/commits/38149ff7a5c2ad1206b02e3ba4544994b31ec967
- The extremely large diff of all the font assets being updated and changed to WOFF2 files: https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/3/commits/27ea8c725c938f448ac95bbde0f79b35a3108b78

Closes https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/1.

## Testing Instructions
- Run `npm run files`
- The font assets that are downloaded should all be `WOFF2` files

### CODE REVIEW

**Comment by pbking** [comment]
I can confirm that the files referenced are WOFF.

The other assets committed to the branch still seem to be ttf though, and I'm not sure why.  What I get locally is woff resources, so the change is right.  I'm just not sure why I see some of the resources I do.

I'm still running the scripts (it takes a while) so maybe I'll know more when it's done.

**Comment by luminuu** [comment]
The generation of the `google-fonts.json` file runs correctly for me and replaces the .ttf file URLs with .woff2 file URLs.

However running `npm run files` causes errors, as the JSON files differ in their setup. A font family in the 16.7 (old) version:

```
{
  "name": "ABeeZee",
  "fontFamily": "ABeeZee, sans-serif",
  "slug": "abeezee",
  "category": "sans-serif",
  "fontFace": [
    {
      "src": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN6tKukbcHCpE.ttf",
      "fontWeight": "400",
      "fontStyle": "normal",
      "fontFamily": "ABeeZee"
    },
    {
      "src": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCklZUCGpG-GQ.ttf",
      "fontWeight": "400",
      "fontStyle": "italic",
      "fontFamily": "ABeeZee"
    }
  ]
},
```

In the new version (17.6) it's slightly different:

```
{
  "font_family_settings": {
    "name": "ABeeZee",
    "fontFamily": "ABeeZee, sans-serif",
    "slug": "abeezee",
    "fontFace": [
      {
        "src": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN6teukbcHCpE.woff2",
        "fontWeight": "400",
        "fontStyle": "normal",
        "fontFamily": "ABeeZee"
      },
      {
        "src": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCkkJUCGpG-GQ.woff2",
        "fontWeight": "400",
        "fontStyle": "italic",
        "fontFamily": "ABeeZee"
      }
    ]
  },
  "categories": [
    "sans-serif"
  ]
},
```

The following lines or variables have to change:
https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/673a2e05ee30273682933d4732b6b27c0106104d/src/download_google_font_assets.js#L17
to `return googleFonts.font_families`

https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/673a2e05ee30273682933d4732b6b27c0106104d/src/download_google_font_assets.js#L49
to `${families[i].font_family_settings.name}`

https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/673a2e05ee30273682933d4732b6b27c0106104d/src/download_google_font_assets.js#L50
to `families[i].font_family_settings.fontFace.length`

https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/673a2e05ee30273682933d4732b6b27c0106104d/src/download_google_font_assets.js#L53
to `const url = families[i].font_family_settings.fontFace[x]['src'];`

With these changes, the font files get downloaded correctly as woff2 files.

**Comment by mikachan** [comment]
Thanks @luminuu! You're right, looks like `download_google_font_assets.js` and `generate_font_previews.js` both needed to be updated to use the new schema. I've updated these in https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/3/commits/49cb83263d81c942da768c48a60f6ac136b7f187.

**Comment by mikachan** [comment]
I'm seeing the following errors when generating the SVG previews: `Error generating preview for Zilla Slab Highlight 700 normal: Error: Unsupported OpenType signature wOF2`

It looks like the library we're using, text-to-svg, doesn't support WOFF files. There's a similar discussion here: https://github.com/opentypejs/opentype.js/issues/360. Maybe we should provide a list of TTF files for the previews to be generated from, and provide a list of WOFF files for the font assets themselves.

Edit: I've spoken to @matiasbenedetto, and we discussed that we don't need to update the previews now and they're also only ever generated in this repo. So we can leave the preview file as it is for now, and handle the above error from text-to-svg in a follow-up.

**Review by matiasbenedetto — CHANGES_REQUESTED** [review]
I think we should avoid committing all the font files (WOFF or ttf) to the repo because we are not tracking changes on it, and they are making the repo big and difficult to handle (Github and vs. code PR previews not working) without a good reason. I think that previously, we were considering hosting the font assets ourselves for the font collection, and because of that, we persisted in the repo, but that's no longer true, so we can remove them.

Could you please remove the WOFF2 font assets from the PR so we can merge it?

I submitted a PR removing the existing TFF files from the repo: https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/5

**Comment by mikachan** [comment]
> Could you please remove the WOFF2 font assets from the PR so we can merge it?

I agree! Thanks for confirming, I'll remove the new files from this PR once https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/5 is merged.

**Comment by matiasbenedetto** [comment]
> I'll remove the new files from this PR once https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/5 is merged.

:+1: Ready!

**Comment by mikachan** [comment]
I've updated this PR by removing font-assets. I also double-checked that the google-fonts.json is still up to date by running `npm run api` again. This is ready for another review, thanks!

**Review by matiasbenedetto — APPROVED** [review]
LGTM

**Pull request merged**
