### PR TITLE
Add 6.7 release

### LINKED ISSUE #34: Update font family collection
I discovered this through an issue in the Gutenberg project: https://github.com/WordPress/gutenberg/issues/64685

Currently, there are fonts that exist in the Google Fonts API but are not in the WordPress font collection. We probably need to update the font collection.

When I update the font collection, the following fonts will be added:

<details><summary>Details</summary>

```
$ GOOGLE_FONTS_API_KEY={MY_API_KEY} npm run api
$ git diff | grep '^+\s*"name"'
+                               "name": "Annapurna SIL",
+                               "name": "Anta",
+                               "name": "Anton SC",
+                               "name": "Arsenal SC",
+                               "name": "Baskervville SC",
+                               "name": "Beiruti",
+                               "name": "Bodoni Moda SC",
+                               "name": "Bona Nova SC",
+                               "name": "Bungee Tint",
+                               "name": "Cactus Classical Serif",
+                               "name": "Chocolate Classical Sans",
+                               "name": "Danfo",
+                               "name": "Edu AU VIC WA NT Hand",
+                               "name": "Freeman",
+                               "name": "Fustat",
+                               "name": "Ga Maamli",
+                               "name": "Honk",
+                               "name": "Jacquard 12",
+                               "name": "Jacquard 12 Charted",
+                               "name": "Jacquard 24",
+                               "name": "Jacquard 24 Charted",
+                               "name": "Jacquarda Bastarda 9",
+                               "name": "Jacquarda Bastarda 9 Charted",
+                               "name": "Jaini",
+                               "name": "Jaini Purva",
+                               "name": "Jaro",
+                               "name": "Jersey 10",
+                               "name": "Jersey 10 Charted",
+                               "name": "Jersey 15",
+                               "name": "Jersey 15 Charted",
+                               "name": "Jersey 20",
+                               "name": "Jersey 20 Charted",
+                               "name": "Jersey 25",
+                               "name": "Jersey 25 Charted",
+                               "name": "Kalnia Glaze",
+                               "name": "Kode Mono",
+                               "name": "LXGW WenKai Mono TC",
+                               "name": "LXGW WenKai TC",
+                               "name": "Madimi One",
+                               "name": "Maname",
+                               "name": "Matemasie",
+                               "name": "Micro 5",
+                               "name": "Micro 5 Charted",
+                               "name": "Moderustic",
+                               "name": "Namdhinggo",
+                               "name": "New Amsterdam",
+                               "name": "Noto Znamenny Musical Notation",
+                               "name": "Ojuju",
+                               "name": "Platypi",
+                               "name": "Playwrite AR",
+                               "name": "Playwrite AT",
+                               "name": "Playwrite AU NSW",
+                               "name": "Playwrite AU QLD",
+                               "name": "Playwrite AU SA",
+                               "name": "Playwrite AU TAS",
+                               "name": "Playwrite AU VIC",
+                               "name": "Playwrite BE VLG",
+                               "name": "Playwrite BE WAL",
+                               "name": "Playwrite BR",
+                               "name": "Playwrite CA",
+                               "name": "Playwrite CL",
+                               "name": "Playwrite CO",
+                               "name": "Playwrite CU",
+                               "name": "Playwrite CZ",
+                               "name": "Playwrite DE Grund",
+                               "name": "Playwrite DE LA",
+                               "name": "Playwrite DE SAS",
+                               "name": "Playwrite DE VA",
+                               "name": "Playwrite DK Loopet",
+                               "name": "Playwrite DK Uloopet",
+                               "name": "Playwrite ES",
+                               "name": "Playwrite ES Deco",
+                               "name": "Playwrite FR Moderne",
+                               "name": "Playwrite FR Trad",
+                               "name": "Playwrite GB J",
+                               "name": "Playwrite GB S",
+                               "name": "Playwrite HR",
+                               "name": "Playwrite HR Lijeva",
+                               "name": "Playwrite HU",
+                               "name": "Playwrite ID",
+                               "name": "Playwrite IE",
+                               "name": "Playwrite IN",
+                               "name": "Playwrite IS",
+                               "name": "Playwrite IT Moderna",
+                               "name": "Playwrite IT Trad",
+                               "name": "Playwrite MX",
+                               "name": "Playwrite NG Modern",
+                               "name": "Playwrite NL",
+                               "name": "Playwrite NO",
+                               "name": "Playwrite NZ",
+                               "name": "Playwrite PE",
+                               "name": "Playwrite PL",
+                               "name": "Playwrite PT",
+                               "name": "Playwrite RO",
+                               "name": "Playwrite SK",
+                               "name": "Playwrite TZ",
+                               "name": "Playwrite US Modern",
+                               "name": "Playwrite US Trad",
+                               "name": "Playwrite VN",
+                               "name": "Playwrite ZA",
+                               "name": "Plus Jakarta Sans",
+                               "name": "Podkova",
+                               "name": "Poetsen One",
+                               "name": "Poiret One",
+                               "name": "Poller One",
+                               "name": "Poltawski Nowy",
+                               "name": "Poly",
+                               "name": "Pompiere",
+                               "name": "Pontano Sans",
+                               "name": "Poor Story",
+                               "name": "Poppins",
+                               "name": "Port Lligat Sans",
+                               "name": "Port Lligat Slab",
+                               "name": "Potta One",
+                               "name": "Protest Guerrilla",
+                               "name": "Protest Revolution",
+                               "name": "Protest Riot",
+                               "name": "Protest Strike",
+                               "name": "Radio Canada Big",
+                               "name": "Reddit Mono",
+                               "name": "Reddit Sans",
+                               "name": "Reddit Sans Condensed",
+                               "name": "Rubik Glitch Pop",
+                               "name": "Sankofa Display",
+                               "name": "Sedan",
+                               "name": "Sedan SC",
+                               "name": "Sixtyfour",
+                               "name": "Tac One",
+                               "name": "Teachers",
+                               "name": "Tiny5",
+                               "name": "Ubuntu Sans",
+                               "name": "Ubuntu Sans Mono",
+                               "name": "Wittgenstein",
+                               "name": "Workbench",
+                               "name": "Yarndings 12",
+                               "name": "Yarndings 12 Charted",
+                               "name": "Yarndings 20",
+                               "name": "Yarndings 20 Charted",
+                               "name": "Zain",
```

</details>

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
1. Add updated font collection for WordPress 6.7 release.
- Font collection with preview URLs.
- New SVG previews.
2. Improve the end stats of the preview creation script.

## Why?
Fixes: https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/34

## How to test?
An easy way to test is to add this snippet to your theme `functions.php` file.
I think the most important thing to verify is:
- Where the [new fonts](https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/34#issuecomment-2422720865) added? Search for 'Reddit' for example.
- Do the previews of those fonts look fine?
- Do the installation process continue working fine? Install a few fonts to test.

```php

function test_updated_font_collection() {
	// Unregister the default google fonts collection
	wp_unregister_font_collection( 'google-fonts' );

	// Register the Google fonts collection but with the new data for the 6.7 release
	wp_register_font_collection(
	  'google-fonts-67',
	  array(
	          // Changing the name of the collection just for testing purposes to see if the changes are working.
		  'name'          => _x( 'Google Fonts 6.7', 'font collection name' ),
		  'description'   => __( 'Install from Google Fonts. Fonts are copied to and served from your site.' ),
		  // Use the new collection data added in https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/38
		  'font_families' => 'https://raw.githubusercontent.com/WordPress/google-fonts-to-wordpress-collection/6bfe35631278c414764b0dd50d4b1a8efe0e1e17/releases/wp-6.7/collections/google-fonts-with-preview.json',
		  'categories'    => array(
			  array(
				  'name' => _x( 'Sans Serif', 'font category' ),
				  'slug' => 'sans-serif',
			  ),
			  array(
				  'name' => _x( 'Display', 'font category' ),
				  'slug' => 'display',
			  ),
			  array(
				  'name' => _x( 'Serif', 'font category' ),
				  'slug' => 'serif',
			  ),
			  array(
				  'name' => _x( 'Handwriting', 'font category' ),
				  'slug' => 'handwriting',
			  ),
			  array(
				  'name' => _x( 'Monospace', 'font category' ),
				  'slug' => 'monospace',
			  ),
		  ),
	  )
	);
}

add_action( 'init', 'test_updated_font_collection' );

```

## Screencast
A screencast showing the collection with the updated data working:

https://github.com/user-attachments/assets/2038611f-60f7-4e3e-98d5-48137b97d1af

## To do after this PR is approved:
1. After this is approved and before merging we need to replace the provisory github base url (`https://raw.githubusercontent.com/WordPress/google-fonts-to-wordpress-collection/9724ef4a38da729f770027359b7decec2fcd29f8/releases/`) by the wporg CDN url (`https://s.w.org/images/fonts/`) in the `google-fonts-with-preview.json` file.
2. Ask meta team to host the JSON file and the SVG previews in the wporg CDN.
3. Change the Google fonts collection url in wordpress-develop repo.

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
@t-hamano I am pinging you in case you can take a look. I don't know why I can't request your review using the sidebar widget.

**Review by mikachan — APPROVED** [review]
This looks good to me based on the way we handled the files for 6.5 👍

**Review by mikachan — APPROVED** [review]
This looks good to me based on the way we handled the files for 6.5 👍

**Comment by t-hamano** [comment]
All the changes look good, but will it be possible to ship this change in 6.7? Because we are already in the 6.7 beta phase.

Personally, I thought the font update would come in 6.8.

> I don't know why I can't request your review using the sidebar widget.

Probably because I'm not a member of this repository 😄 I'd be happy to be added as a member if you'd like.

**Comment by matiasbenedetto** [comment]
> I'm not a member of this repository 😄

:+1:  I just added you

**Pull request merged**
